### ISSUE TITLE
KeyError: 'sshd'

### ISSUE THREAD

**Issue by laemm-line** [vdcloudcraft/fail2ban-geo-exporter#14]
Hello,

I get the following error when I try to start the exporter:

```
Traceback (most recent call last):
  File "/f2b-exporter/fail2ban-exporter.py", line 127, in <module>
    REGISTRY.register(F2bCollector(conf))
  File "/usr/lib/python3.7/site-packages/prometheus_client/registry.py", line 24, in register
    names = self._get_names(collector)
  File "/usr/lib/python3.7/site-packages/prometheus_client/registry.py", line 64, in _get_names
    for metric in desc_func():
  File "/f2b-exporter/fail2ban-exporter.py", line 76, in collect
    self.get_jailed_ips()
  File "/f2b-exporter/fail2ban-exporter.py", line 59, in get_jailed_ips
    bantime = config[j[0]]['bantime'].split(';')[0].strip()
  File "/usr/lib/python3.7/configparser.py", line 958, in __getitem__
    raise KeyError(key)
KeyError: 'sshd'
```

**Comment by evanrich** [comment]
same here.

Update: I've tried the "latest" docker image as well as cloning the repo, and both have this issue, so seems something broke...probably a fail2ban update or something.

**Comment by evanrich** [comment]
@vdcloudcraft  do you check in on this repo, or is it abandonware?

**Comment by ticteam** [comment]
same here. 

is it still supported ?

**Comment by jdd272** [comment]
Hi, I've come into the same exact issue. Found out it was because my jail's config file was a *.conf, when the software actually looks for *.local. Rename that and it should work ! cheers

**Comment by Kontr3X** [comment]
This issue belongs to: https://github.com/vdcloudcraft/fail2ban-geo-exporter/issues/19
